--
date: YYYY-MM-DD
theme: minima
title: "The land of nowhere"
author: chuadoNeblod
email: octavio_reina14613@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Web Page Development"
# social links
twitter_username: drago_guitar # DO NOT include the @ character, or else the build will fail!
github_username:  ChuadoNeblod # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
--
